*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus
master.sink.prometheusServlet.path=/metrics/master/prometheus
applications.sink.prometheusServlet.path=/metrics/applications/prometheus
driver.sink.prometheusServlet.path=/metrics/driver/prometheus
executor.sink.prometheusServlet.path=/metrics/executors/prometheus